/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      animation: {
        type: "type 6s infinite",
      },
      keyframes: {
        type: {
          "0%, 20%": { transform: "translateX(0ch)" },
          "22%, 24%": { transform: "translateX(1ch)" },
          "26%, 28%": { transform: "translateX(2ch)" },
          "30%, 32%": { transform: "translateX(3ch)" },
          "34%, 36%": { transform: "translateX(4ch)" },
          "38%, 40%": { transform: "translateX(5ch)" },
          "42%, 44%": { transform: "translateX(6ch)" },
          "46%, 48%": { transform: "translateX(7ch)" },
          "50%, 52%": { transform: "translateX(8ch)" },
          "54%, 56%": { transform: "translateX(9ch)" },
          "58%, 60%": { transform: "translateX(10ch)" },
          "62%, 64%": { transform: "translateX(11ch)" },
          "66%, 68%": { transform: "translateX(12ch)" },
          "70%, 72%": { transform: "translateX(13ch)" },
          "74%, 76%": { transform: "translateX(14ch)" },
          "78%, 80%": { transform: "translateX(15ch)" },
          "%, %": { transform: "translateX(14ch)" },
          "%, %": { transform: "translateX(13ch)" },
          "%, %": { transform: "translateX(12ch)" },
          "%, %": { transform: "translateX(11ch)" },
          "%, %": { transform: "translateX(10ch)" },
          "%, %": { transform: "translateX(9ch)" },
          "%, %": { transform: "translateX(8ch)" },
          "%, %": { transform: "translateX(7ch)" },
          "%, %": { transform: "translateX(6ch)" },
          "%, %": { transform: "translateX(5ch)" },
          "%, %": { transform: "translateX(4ch)" },
          "%, %": { transform: "translateX(3ch)" },
          "%, %": { transform: "translateX(2ch)" },
          "%, %": { transform: "translateX(1ch)" },
          "100%": { transform: "translateX(0ch)" },
        },
      },
    },
  },
  plugins: [],
};
