/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      animation: {
        type: "type 6s infinite",
      },
      keyframes: {
        type: {
          "0%": { transform: "translateX(0ch)" },
          "2%, 4%": { transform: "translateX(1ch)" },
          "6%, 8%": { transform: "translateX(2ch)" },
          "10%, 12%": { transform: "translateX(3ch)" },
          "14%, 16%": { transform: "translateX(4ch)" },
          "18%, 20%": { transform: "translateX(5ch)" },
          "22%, 24%": { transform: "translateX(6ch)" },
          "26%, 28%": { transform: "translateX(7ch)" },
          "30%, 32%": { transform: "translateX(8ch)" },
          "34%, 36%": { transform: "translateX(9ch)" },
          "38%, 40%": { transform: "translateX(10ch)" },
          "42%, 44%": { transform: "translateX(11ch)" },
          "46%, 48%": { transform: "translateX(12ch)" },
          "50%, 52%": { transform: "translateX(13ch)" },
          "54%, 56%": { transform: "translateX(14ch)" },
          "58%, 70%": { transform: "translateX(15ch)" },
          "71%": { transform: "translateX(14ch)" },
          "72%": { transform: "translateX(13ch)" },
          "73%": { transform: "translateX(12ch)" },
          "74%": { transform: "translateX(11ch)" },
          "75%": { transform: "translateX(10ch)" },
          "76%": { transform: "translateX(9ch)" },
          "77%": { transform: "translateX(8ch)" },
          "79%": { transform: "translateX(7ch)" },
          "80%": { transform: "translateX(6ch)" },
          "81%": { transform: "translateX(5ch)" },
          "82%": { transform: "translateX(4ch)" },
          "83%": { transform: "translateX(3ch)" },
          "84%": { transform: "translateX(2ch)" },
          "85%": { transform: "translateX(1ch)" },
          "86%, 100%": { transform: "translateX(0ch)" },
        },
      },
    },
  },
  plugins: [],
};
